Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -121,7 +121,11 @@ jobs:
       - checkout
       - run:
           name: Heroku Deploy
-          command: echo todo && false
+          command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://salty-journey-63595.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+            echo "heroku app not responding, failing deploy"
+            exit 1
+            fi
       - run:
           name: Smoke Test
           command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://salty-journey-63595.herokuapp.com/`
