Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -124,7 +124,11 @@ jobs:
           command: echo todo && false
       - run:
           name: Smoke Test
-          command: echo todo && false
+          command: HTTPCODE=`curl -s -o /dev/null -w "%{http_code}" https://salty-journey-63595.herokuapp.com/`
+            if [ "$HTTPCODE" -ne 200 ];then
+            echo "heroku app not responding, failing deploy"
+            exit 1
+            fi
 
 workflows:
   version: 2
